module.exports = {
    0: {
        ignoreSpam: false,
        view: true
    },
    1: {
        ignoreSpam: true,
        view: true
    },
    2: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        seeChatlogs: true,
        view: true
    },
    3: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        viewChannelLog: true,
        view:true,
        viewChannels:true
    },
    4: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        viewChannelLog: true,
        view:true,
        viewChannels:true
    },
    5: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        manageManager: true,
        viewChannelLog: true,
        view:true,
        viewChannels:true
    },
    6: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        manageManager: true,
        viewChannelLog: true,
        view:true,
        viewChannels:true
    },
    7: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        manageManager: true,
        viewChannelLog: true,
        managePictures: true,
        view:true,
        viewChannels:true
    },
    8: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        manageManager: true,
        viewChannelLog: true,
        managePictures: true,
        view:true,
        viewChannels:true
    },
    9: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        manageManager: true,
        viewChannelLog: true,
        managePictures: true,
        view:true,
        viewChannels:true
    },
    10: {
        ignoreSpam: true,
        createTwitch: true,
        createVCS: true,
        deleteTwitch: true,
        deleteVCS: true,
        purge: true,
        prefixAdd: true,
        seeChatlogs: true,
        manageSpam: true,
        manageModerator: true,
        manageVip: true,
        manageRegular: true,
        manageManager: true,
        viewChannelLog: true,
        managePictures: true,
        view:true,
        viewChannels:true
    }
};